### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sarah872** [BDM-Lab/Hierarchical3DGenome#2]
Hi,
I am getting the following error when running it my files:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at full_modeling.HierarchicalModeling.main(HierarchicalModeling.java:53)
	... 5 more
```

```
java -jar HierarchicalModeller_v1.jar 1 5000 raw.txt balanced.txt domains.txt output
```
[raw.txt.gz](https://github.com/BDM-Lab/Hierarchical3DGenome/files/6345064/raw.txt.gz)
[balanced.txt.gz](https://github.com/BDM-Lab/Hierarchical3DGenome/files/6345065/balanced.txt.gz)
[domains.txt](https://github.com/BDM-Lab/Hierarchical3DGenome/files/6345067/domains.txt)

**Comment by oluwatosin-oluwadare** [comment]
> Hi,
> I am getting the following error when running it my files:
> 
> ```
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
> 	at full_modeling.HierarchicalModeling.main(HierarchicalModeling.java:53)
> 	... 5 more
> ```
> 
> ```
> java -jar HierarchicalModeller_v1.jar 1 5000 raw.txt balanced.txt domains.txt output
> ```
> 
> [raw.txt.gz](https://github.com/BDM-Lab/Hierarchical3DGenome/files/6345064/raw.txt.gz)
> [balanced.txt.gz](https://github.com/BDM-Lab/Hierarchical3DGenome/files/6345065/balanced.txt.gz)
> [domains.txt](https://github.com/BDM-Lab/Hierarchical3DGenome/files/6345067/domains.txt)

From your input data, we observed two problems:
1) **The input you provided is not in the recommended format to run the tool:**
We observed that you provided a matrix bin position index(1,2, 3,4) instead of genomic position location(880000, 100000) for your contact matrices from your input data. 
** In the format documentation for the observed and normalized contact frequency provided here https://github.com/BDM-Lab/Hierarchical3DGenome, we mentioned that the format for the contact takes the sparse input represented as :
_Observed_contact_data_: observed hi-C contact file, each line contains 3 numbers (separated by a space) of a contact, position_1 position_2 interaction_frequencies 
_normalized_contact_data_: normalized Hi-C contact file, each line contains 3 numbers (separated by a space) of a contact, position_1 position_2 interaction_frequencies 
See example input here: http://sysbio.rnet.missouri.edu/bdm_download/Hierarchical3DGenome/Hierarchical3DGenome/input_sample/chr10_5kb.RAWobserved

**2) Your inputs are inconsistent:**
You provided your input matrix in Hi-C matrix bin position, but your domain file is in genomic position formats. If the tools is to work, it needs to be able to locate the TADs on the contact matrix based on the genomic position formats. Hence even though your domains are in the right form, the contact data format does not help.

3) **You domain file only contains only one domain (Note this)**
This tool builds 3D structures using domains. It builds a structure per domain and connects them to form a final 3D structure, hence the  name Hierarchical3DGenome. Your current input domain file has one domain. This is something you want to look into too.

Finally, hierarchical3DGenome works when all the input are in the right format and even though it doesn't give direct messages when it fails, from experience, this usually happens when the inputs provided are not in the right format. Please review and execute the sample inputs we provided to see how the tool works. Thanks.
